service: my-serverless-app

provider:
 name: aws
 runtime: nodejs12.x
 memorySize: 128
 timeout: 10
 stage: api
 region: eu-central-1

functions:
 api:
   handler: lambda.universal
   events:
     - http: ANY {proxy+}
     - http: ANY /
   environment :
     THEMOVIEDBAPIKEY : ${file(./config.js):fetchApiKey}
     THEMOVIEAPIRURL : ${file(./config.js):fetchApiUrl}